import type { Metadata } from "next";
import Image from "next/image";
import { Backdrop } from "@/components/ui/backdrop";
import { Footer } from "@/components/footer";
import { Interactions } from "@/components/interactions";
import { Nav } from "@/components/nav";
import { Card, Eyebrow, Reveal } from "@/components/ui/primitives";
import { Work } from "@/components/work";
import { siteConfig } from "@/config/site";
import { StructuredData } from "@/components/structured-data";

export const metadata: Metadata = {
  title: "About Conscious Rise",
  description: "Meet Tejinder Singh, the developer behind Conscious Rise, and learn about the hands-on experience shaping the studio.",
  alternates: { canonical: "/about" },
  openGraph: { title: "About Conscious Rise", description: "A practical web engineering studio focused on clear thinking, careful implementation and dependable delivery.", url: "/about", images: ["/og-image.jpg"] },
  twitter: { title: "About Conscious Rise", description: "A practical web engineering studio focused on clear thinking and dependable delivery.", images: ["/og-image.jpg"] },
};

const facts = [
  ["6+", "Years Experience"],
  ["70+", "Projects"],
  ["Global", "Clients"],
  ["Full-Stack", "Development"],
] as const;
const principles = [
  { number: "01", title: "Clarity before code", body: "Every project starts by understanding the goal, audience and constraints. The right solution is not always the most complicated one, and a simpler build is recommended when it serves the business better." },
  { number: "02", title: "Care in the details", body: "Responsive states, loading speed, accessibility and the small interactions between screens are part of the work, not optional polish added at the end." },
  { number: "03", title: "Communication you can rely on", body: "Progress stays visible, questions are raised early and timelines remain grounded in what can be delivered well." },
];
const capabilities = ["Website design & development", "No-code & low-code solutions", "Custom web applications", "AI & workflow automation", "API & system integrations", "E-commerce experiences", "Performance & technical SEO"];

export default function AboutPage() {
  return <><Backdrop /><StructuredData data={{ "@context": "https://schema.org", "@type": "AboutPage", url: `${siteConfig.url}/about`, mainEntity: { "@id": `${siteConfig.url}/#founder` }, breadcrumb: { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteConfig.url }, { "@type": "ListItem", position: 2, name: "About", item: `${siteConfig.url}/about` }] } }} /><Interactions /><Nav />
    <main id="main" className="internal-page overflow-hidden pt-24">
      <section className="relative pb-20 pt-16 sm:pb-28 sm:pt-24"><div aria-hidden className="absolute -left-44 top-8 h-96 w-96 rounded-full bg-neon-fuchsia/[0.08] blur-3xl" /><div aria-hidden className="absolute -right-40 top-56 h-96 w-96 rounded-full bg-neon-cyan/[0.07] blur-3xl" /><div className="container-x relative">
        <div className="grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-20"><div><Reveal><Eyebrow>About the founder</Eyebrow></Reveal><Reveal delay={70}><h1 className="mt-6 max-w-5xl font-display text-[clamp(3.25rem,7vw,6.6rem)] font-semibold leading-[0.94] tracking-[-0.055em] text-white">Built on real<br /><span className="text-gradient">experience.</span></h1></Reveal><Reveal delay={130}><p className="mt-8 text-lg leading-8 text-white/70">I&apos;ve been working in web development since 2019, starting alongside an experienced freelancer and later working professionally as a Web Developer from 2022 to 2024.</p></Reveal><Reveal delay={190}><p className="mt-5 text-lg leading-8 text-white/55">In 2024, I began working independently with businesses and clients worldwide, building websites and digital experiences across Webflow, Framer, WordPress, and modern custom development.</p></Reveal><Reveal delay={240}><p className="mt-5 text-lg leading-8 text-white/55">Today, that experience is the foundation behind <strong className="font-semibold text-white">Conscious Rise</strong> — combining years of hands-on development with a focus on building digital solutions that help businesses grow.</p></Reveal><Reveal delay={290}><div className="mt-9 flex flex-wrap gap-3"><a href="/contact" className="rounded-full bg-[#991b3b] px-6 py-3.5 text-sm font-semibold text-[#ffffff] shadow-lg transition-all hover:-translate-y-0.5 hover:bg-[#bc244a]">Start a project</a><a href="/work" className="group inline-flex items-center gap-2 rounded-full border border-neon-cyan/20 bg-[#ffffff] px-6 py-3.5 text-sm font-semibold text-[#4a0d1d] shadow-[0_10px_30px_-20px_rgba(119,12,38,0.5)] transition-all hover:-translate-y-0.5 hover:border-neon-cyan/40">See the work <span aria-hidden>→</span></a></div></Reveal></div>
        <Reveal delay={120} className="mx-auto w-full max-w-[34rem]"><div className="about-photo-float relative"><div aria-hidden className="absolute -inset-4 -rotate-3 rounded-[2.2rem] border border-neon-cyan/10 bg-[#fff6f7]" /><div aria-hidden className="about-orbit absolute -right-8 -top-8 h-20 w-20 rounded-full border border-dashed border-neon-cyan/30" /><div aria-hidden className="absolute -bottom-7 -left-7 grid h-16 w-16 place-items-center rounded-full border border-neon-cyan/15 bg-[#ffffff] shadow-lg"><span className="font-mono text-[.58rem] uppercase tracking-[.14em] text-white/50">Since<br />2019</span></div><div className="relative overflow-hidden rounded-[2rem] border border-neon-cyan/20 bg-[#ffffff] p-2 shadow-[0_30px_90px_-40px_rgba(119,12,38,.45)]"><div className="relative aspect-[5/6.4] overflow-hidden rounded-[1.55rem] bg-[#f5efeb]"><Image src={siteConfig.founderPhoto} alt={`${siteConfig.founderName}, Founder and Technical Lead at Conscious Rise`} fill sizes="(max-width: 1024px) 90vw, 42vw" quality={100} className="object-cover object-top" /><div aria-hidden className="absolute inset-x-0 bottom-0 h-36 bg-gradient-to-t from-[#3f0c19]/45 to-transparent" /><div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-[#ffffff]/20 bg-[#4a0d1d]/90 p-4 shadow-xl backdrop-blur-md"><p className="font-display text-lg font-semibold text-[#ffffff]">{siteConfig.founderName}</p><p className="mt-0.5 text-xs text-[#ffffff]/60">Founder &amp; Technical Lead · Conscious Rise</p></div></div></div></div></Reveal></div>
        <div className="mt-20 grid overflow-hidden rounded-3xl border border-neon-cyan/15 bg-[#ffffff] shadow-[0_18px_50px_-34px_rgba(119,12,38,0.32)] sm:grid-cols-2 lg:grid-cols-4">{facts.map(([value, label], index) => <Reveal key={label} delay={index * 70} className="group relative overflow-hidden border-b border-neon-cyan/10 p-7 last:border-b-0 sm:border-r sm:p-9 lg:border-b-0 lg:last:border-r-0"><span aria-hidden className="absolute -right-2 -top-7 font-display text-[7rem] font-bold leading-none text-[#4a0d1d]/[0.025]">0{index + 1}</span><p className="relative font-display text-4xl font-semibold tracking-[-0.04em] text-white">{value}</p><p className="relative mt-2 text-sm text-white/50">{label}</p></Reveal>)}</div>
      </div></section>
      <Work />
      <section className="py-20 sm:py-28"><div className="container-x grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><Reveal><div className="lg:sticky lg:top-32"><Eyebrow>The approach</Eyebrow><h2 className="mt-5 font-display text-[clamp(2.2rem,4vw,3.4rem)] font-semibold leading-[1.04] tracking-[-0.04em] text-white">Built around the outcome.</h2></div></Reveal><div className="space-y-7 text-lg leading-8 text-white/58"><Reveal><p>Projects begin with the business outcome, not a predetermined platform. That keeps the recommendation honest and the implementation appropriate to the job.</p></Reveal><Reveal delay={70}><p>Experience across marketing websites, custom applications, no-code builds, commerce and connected systems makes it possible to choose the right level of complexity without forcing every project into the same technology.</p></Reveal><Reveal delay={140}><p>The finished work should be quick to load, easy to understand, straightforward to update and solid enough to grow with the business behind it. Good design earns attention; thoughtful engineering keeps earning trust after launch.</p></Reveal><Reveal delay={200}><blockquote className="rounded-2xl border border-neon-cyan/15 bg-[#fff7f8] px-7 py-7 font-display text-[1.35rem] font-medium leading-relaxed text-white shadow-[0_18px_50px_-38px_rgba(119,12,38,0.45)] sm:px-9">Clients should understand what is being built, why it is being built that way, and what they will own when the work is done.</blockquote></Reveal></div></div></section>
      <section className="py-20 sm:py-28"><div className="container-x"><Reveal className="max-w-3xl"><Eyebrow>How projects run</Eyebrow><h2 className="mt-5 font-display text-[clamp(2.2rem,4vw,3.4rem)] font-semibold leading-[1.04] tracking-[-0.04em] text-white">A straightforward way of working.</h2></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{principles.map((item, index) => <Reveal key={item.number} delay={index * 80} className="h-full"><Card className="h-full p-7 sm:p-9"><div className="relative z-10"><span className="font-mono text-xs tracking-[0.2em] text-neon-cyan">{item.number}</span><h3 className="mt-8 font-display text-2xl font-semibold text-white">{item.title}</h3><p className="mt-4 text-lg leading-8 text-white/52">{item.body}</p></div></Card></Reveal>)}</div></div></section>
      <section className="pb-24 pt-16 sm:pb-32 sm:pt-24"><div className="container-x"><div className="overflow-hidden rounded-[2rem] bg-[#4a0d1d] px-7 py-12 text-[#ffffff] sm:px-12 sm:py-16 lg:px-16"><div className="grid items-center gap-12 lg:grid-cols-[1fr_.85fr]"><Reveal><p className="font-mono text-[.68rem] uppercase tracking-[.22em] text-[#ffb0c0]">What Conscious Rise builds</p><h2 className="mt-5 max-w-2xl font-display text-[clamp(2.25rem,4.5vw,4rem)] font-semibold leading-[1.03] tracking-[-.045em]">The right platform, built with care.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-[#ffffff]/60">From a focused marketing website to a custom application, an existing design can be taken into production or the solution can be shaped from the beginning.</p></Reveal><Reveal delay={100}><ul className="grid gap-2 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2">{capabilities.map((item) => <li key={item} className="flex items-center gap-3 rounded-xl border border-[#ffffff]/10 bg-[#ffffff]/[.045] px-4 py-3 text-sm text-[#ffffff]/75"><span className="text-[#ff8ca5]">↗</span>{item}</li>)}</ul></Reveal></div><Reveal delay={160}><div className="mt-12 flex flex-col items-start justify-between gap-6 border-t border-[#ffffff]/10 pt-8 sm:flex-row sm:items-center"><p className="max-w-xl text-lg leading-8 text-[#ffffff]/55">Have a project in mind? Share what the business is trying to achieve and receive practical questions and a clear next step.</p><a href="/contact" className="shrink-0 rounded-full bg-[#ffffff] px-6 py-3.5 text-sm font-semibold text-[#4a0d1d]">Start a conversation</a></div></Reveal></div></div></section>
    </main><Footer /></>;
}
